# .github/workflows/build-windows.yml
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: 下载 Python 源码包
        run: |
          Invoke-WebRequest `
            -Uri https://www.python.org/ftp/python/3.12.11/Python-3.12.11.tgz `
            -OutFile Python-3.12.11.tgz

      - name: 解压源码
        shell: bash
        run: |
          mkdir python-src
          tar -xzf Python-3.12.11.tgz -C python-src --strip-components=1

      - name: 安装 MSI 构建依赖
        working-directory: python-src/Tools/msi
        shell: powershell
        run: .\get_externals.bat

      - name: 编译并生成安装包布局 (x64)
        working-directory: python-src/Tools/msi
        shell: powershell
        run: .\build.bat -x64

      - name: 收集并上传安装程序产物
        uses: actions/upload-artifact@v3
        with:
          name: python-3.12.11-win-amd64-installer
          retention-days: 1
          path: |
            python-src/PCbuild/amd64/en-us/*.exe
            python-src/PCbuild/amd64/en-us/*.msi
            python-src/PCbuild/amd64/en-us/*.cab
