name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: 下载 Python 源码包
        run: |
          Invoke-WebRequest `
            -Uri https://www.python.org/ftp/python/3.12.11/Python-3.12.11.tgz `
            -OutFile Python-3.12.11.tgz

      - name: 解压源码
        shell: bash
        run: |
          mkdir python-src
          tar -xzf Python-3.12.11.tgz -C python-src --strip-components=1

      - name: 安装 MSI 构建依赖（WiX Toolset 等）
        working-directory: python-src/Tools/msi
        shell: powershell
        run: .\get_externals.bat

      - name: 禁用文档模块（注释 build.bat 中构建 doc 的部分）
        shell: powershell
        run: |
          (Get-Content python-src/Tools/msi/build.bat) `
            -replace 'call :Build doc %\*', 'REM call :Build doc %*' `
            -replace 'call :Build tcltk %\*', 'REM call :Build tcltk %*' |
          Set-Content python-src/Tools/msi/build.bat

      - name: 编译并生成安装包布局 (x64)
        working-directory: python-src/Tools/msi
        shell: cmd
        run: build.bat -x64 --no-include-tests --no-docs --no-tcltk --no-include-symbols

      - name: 收集并上传安装程序产物
        uses: actions/upload-artifact@v4
        with:
          name: python-3.12.11-win-amd64-installer
          path: |
            python-src/PCbuild/amd64/en-us/*.exe
            python-src/PCbuild/amd64/en-us/*.msi
            python-src/PCbuild/amd64/en-us/*.cab
          retention-days: 1
          compression-level: 0
